### ISSUE TITLE
Wrong keyboard handling

### ISSUE THREAD

**Issue by janmisar** [thefuntasty/FuntastyKit#46]
[`KeyboardHeightConstraint`](https://github.com/thefuntasty/FuntastyKit/blob/master/Sources/AutoLayout/KeyboardHeightConstraint.swift) is controlled only by notifications `.UIKeyboardWillHide` and `.UIKeyboardWillShow` which is not enough. Keyboard can change its height without show/hide (eg. when you switch to emoji keyboard or any custom keyboard).

It's better to use [`.UIKeyboardWillChangeFrame`](https://developer.apple.com/documentation/uikit/uikeyboardwillchangeframenotification)

**Comment by mkj-is** [comment]
Thank you for reporting this issue, have you tried it? Does it work better in some cases? We currently use this and it works correctly even for your example, since the system sends us the show notification when the user selects the emoji keyboard.

**Comment by janmisar** [comment]
I used to do it same way as you (willShow/willHide) and it didn't work as far as I remember 🤔 I will try it if you say it works 🤓

**Comment by janmisar** [comment]
I tested it and you seem to be right 👍 I'm curious why I switched to "willChangeFrame way" some time ago cause I'm sure I had a reason 😄
